# Generated by Django 5.2.13 on 2026-04-09 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='الرابط')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='نبذة مختصرة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('author', models.CharField(default='LUXARO', max_length=100, verbose_name='الكاتب')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='صورة المقال')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='وصف SEO')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, verbose_name='كلمات مفتاحية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
            ],
            options={
                'verbose_name': 'مقال',
                'verbose_name_plural': 'المقالات',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='المدينة')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='عدد الطلبات')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي المشتريات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
            ],
            options={
                'verbose_name': 'العميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='رابط المنتج')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الحالي')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر الأصلي')),
                ('discount_percentage', models.IntegerField(default=0, verbose_name='نسبة الخصم')),
                ('colors', models.JSONField(default=list, verbose_name='الألوان المتاحة')),
                ('sizes', models.JSONField(default=list, verbose_name='المقاسات المتاحة')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='الكمية المتاحة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='منتج مميز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='الصورة الرئيسية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
            ],
            options={
                'verbose_name': 'المنتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الطلب')),
                ('customer_name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('customer_address', models.CharField(max_length=200, verbose_name='العنوان')),
                ('city', models.CharField(max_length=50, verbose_name='المدينة')),
                ('color', models.CharField(max_length=50, verbose_name='اللون المختار')),
                ('size', models.CharField(max_length=10, verbose_name='المقاس المختار')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'قيد المعالجة'), ('confirmed', 'تم التأكيد'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'الطلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='التقييم')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافق عليه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'التقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-created_at'],
            },
        ),
    ]
