# Generated by Django 5.2.12 on 2026-04-10 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='رابط التصنيف')),
                ('description', models.TextField(blank=True, verbose_name='وصف التصنيف')),
                ('main_image_width', models.PositiveIntegerField(default=800, verbose_name='عرض الصورة الرئيسية')),
                ('main_image_height', models.PositiveIntegerField(default=800, verbose_name='ارتفاع الصورة الرئيسية')),
                ('thumbnail_width', models.PositiveIntegerField(default=400, verbose_name='عرض الصورة المصغرة')),
                ('thumbnail_height', models.PositiveIntegerField(default=500, verbose_name='ارتفاع الصورة المصغرة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'التصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category', verbose_name='التصنيف'),
        ),
    ]
